#!/usr/bin/bash

rm -rf /tmp/test.tar /tmp/dettar.*

t=$(mktemp -d /tmp/dettar.XXXX)
cd "$t"

# files with different size
for i in $(seq 1 1025); do 
	dd if=/dev/urandom of=$i.dat bs=$i count=1 2>/dev/null
done

# files with different name length. In order to include files with filenames which are exactly around 512 bytes, we put them in a directory of 250 A and 250 B
mkdir -p "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
for i in $(seq 1 256); do 
	dd if=/dev/urandom of=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB/$(python -c "print('a'*$i)").dat bs=$i count=1 2>/dev/null
done

# now we create crazy symlinks
echo symlinkcontent > symlink0
last=0
for i in $(seq 1 40); do
	ln -s symlink$last symlink$i
	last=$i
done
cd -

sleep 1
touch $t/127.dat
sleep 1
touch $t/192.dat
sleep 1
# now, we change the time for some files
mv $t/127.dat $t/127.dat.old
sleep 1
cp $t/127.dat.old $t/127.dat
sleep 1
rm $t/127.dat.old
sleep 1
touch $t/128.dat

echo $t
